# Site settings
title: Senai Software
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "senaisoftware.github.io" # the base hostname & protocol for your site
twitter_username: senaisoftware
github_username:  senaisoftware

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']