# Site settings
title: Software Senai
email: senai.software@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Blog para disseminação de conhecimentos para área de software, desenvolvidas dentro do SENAI Cimatec em Salvador.

baseurl: ""
url: "senaisoftware.github.io" # the base hostname & protocol for your site
twitter_username: senaisoftware
github_username:  senaisoftware

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']